# Copie para .streamlit/secrets.toml e preencha

[slack]
webhook_url = "https://hooks.slack.com/services/XXX/YYY/ZZZ"

[dw_vissimo]
host = "your-redshift-host"
port = 5439
dbname = "your-db"
user = "your-user"
password = "your-password"
# Opcional para Kestra via JDBC: url = "jdbc:postgresql://host:port/db?ssl=true"

[postgres]
host = "your-postgres-host"
port = 5432
dbname = "your-db"
user = "your-user"
password = "your-password"
# Opcional para Kestra via JDBC: url = "jdbc:postgresql://host:port/db?ssl=true"

[jira]
base_url = "https://your-domain.atlassian.net"
email = "user@company.com"
api_token = "your-jira-api-token"

[kestra]
base_url = "https://kestra.company.com"
tenant = "main"
api_key = "your-kestra-api-key"
